[package]
name = "chess"
version = "0.1.1"
edition = "2021"

[dependencies]
ggez = "0.9.3"
rand = "0.8.5"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.16.0", features = ["v4"] }
